# Generated by Django 5.2.3 on 2025-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=(
                    "topic", "knowledge_base"
                ), name="unique_category_per_kb"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("article", "employee"),
                name="unique_rating_per_article_employee",
            ),
        ),
    ]
