# Generated by Django 5.2.3 on 2025-07-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_bases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
    ]
